"""update table models

Revision ID: 4386052612b5
Revises: 6efd9ea9c83d
Create Date: 2026-02-18 18:31:12.486487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4386052612b5'
down_revision: Union[str, Sequence[str], None] = '6efd9ea9c83d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'players_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('players_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
