"""add shootout fields and matches table

Revision ID: 4dcfd2a7c39c
Revises: b9d1c8c09bb4
Create Date: 2026-03-12 16:18:22.900087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dcfd2a7c39c'
down_revision: Union[str, Sequence[str], None] = 'b9d1c8c09bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=False),
    sa.Column('score1', sa.Integer(), nullable=False),
    sa.Column('score2', sa.Integer(), nullable=False),
    sa.Column('is_extra_time', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['player1_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('game_results', 'is_extra_time',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('tournaments', sa.Column('win_shootout', sa.Integer(), nullable=False))
    op.add_column('tournaments', sa.Column('lose_shootout', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'lose_shootout')
    op.drop_column('tournaments', 'win_shootout')
    op.alter_column('game_results', 'is_extra_time',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('matches')
    # ### end Alembic commands ###
