"""small changes

Revision ID: 6efd9ea9c83d
Revises: d6cd820858e0
Create Date: 2026-02-18 15:36:29.900709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6efd9ea9c83d'
down_revision: Union[str, Sequence[str], None] = 'd6cd820858e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'positions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('positions', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
