"""changed Users class

Revision ID: d6cd820858e0
Revises: e5a4f49ded40
Create Date: 2026-02-16 23:22:17.710466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6cd820858e0'
down_revision: Union[str, Sequence[str], None] = 'e5a4f49ded40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('positions', sa.Integer(), nullable=False))
    op.drop_column('users', 'tg_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tournaments', 'positions')
    # ### end Alembic commands ###
