"""create new table

Revision ID: e5a4f49ded40
Revises: 6667a5670c09
Create Date: 2026-02-16 19:51:49.325610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a4f49ded40'
down_revision: Union[str, Sequence[str], None] = '6667a5670c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('players_id', sa.Integer(), nullable=False),
    sa.Column('players_name', sa.String(), nullable=True),
    sa.Column('players_command', sa.String(), nullable=True),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('games_win', sa.Integer(), nullable=False),
    sa.Column('games_lose', sa.Integer(), nullable=False),
    sa.Column('win_extra_time', sa.Integer(), nullable=False),
    sa.Column('lose_extra_time', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('missed_goals', sa.Integer(), nullable=False),
    sa.Column('score_goals', sa.Integer(), nullable=False),
    sa.Column('different_goals', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['players_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
