"""описание

Revision ID: ea4b71d6f6c4
Revises: 9895d2ed37c9
Create Date: 2026-03-02 23:38:50.901207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4b71d6f6c4'
down_revision: Union[str, Sequence[str], None] = '9895d2ed37c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tg_username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tg_username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
