"""new string

Revision ID: fd3a6e41bedb
Revises: 8d14dfeca901
Create Date: 2026-03-12 16:54:32.256671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd3a6e41bedb'
down_revision: Union[str, Sequence[str], None] = '8d14dfeca901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_results', sa.Column('is_shootout', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_results', 'is_shootout')
    # ### end Alembic commands ###
